remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
- jekyll-remote-theme
title: Zella Sel'Darro
description: A document housing the backstory and related links/articles for the character, Zella Sel'Darro.
